### ISSUE TITLE
Searhing for item gives sql error

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/AoWoW#3]
when you search for an item, you get following error

`SQL Error: Unknown column 'faction_A' in 'where clause' at /var/www/AoWoW/search.php line 107
Array
(
    [code] => 1054
    [message] => Unknown column 'faction_A' in 'where clause'
    [query] => 
        SELECT`name`,`subname`,`minlevel`,`maxlevel`,`type`,`rank`,`A`,`H`, c.entry

```
    FROM aowow_factiontemplate, creature_template c

    WHERE
        (name LIKE '%sword%'
        OR subname LIKE '%sword%'
        )
        AND factiontemplateID=faction_A

[context] => /var/www/AoWoW/search.php line 107
```

)

there are tons more, basically every table thats different in the code then OC will have these kinds of errors. :p`

**Comment by ekzobam** [comment]
fixed
