### ISSUE TITLE
Fatal error: Call to undefined function mass_define() in 

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/AoWoW#4]
Revision: https://github.com/OregonCore/AoWoW/commit/0e67a6374a924d73b245cefa0f9ef53b67d5e5a1

when you want to search for something.

Fatal error: Call to undefined function mass_define() in /var/www/AoWoW/includes/alllocales.php on line 374

seems something went wrong with rewriting alllocales

**Comment by ekzobam** [comment]
fixed [8b3952d](https://github.com/OregonCore/AoWoW/commit/9988f15f1d1943d592e427320e64ad0221be327c)
