### ISSUE TITLE
Error when creature uses smartai

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/AoWoW#5]
i think its because of the abilities that it must show.

but when you select a creature with smartai script attached to it.
the following error occurs:

SQL Error: Unknown column 'entryorguid' in 'where clause' at /var/www/AoWoW/npc.php line 109
Array
(
    [code] => 1054
    [message] => Unknown column 'entryorguid' in 'where clause'
    [query] => SELECT action1_param1 FROM creature_ai_scripts WHERE entryorguid=117 AND action1_type=11
    [context] => /var/www/AoWoW/npc.php line 109
)

**Comment by ekzobam** [comment]
fixed
