### ISSUE TITLE
sql error when writing comment

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/AoWoW#6]
i have added all sql and when you write a comment.. you get the following error.

SQL Error: Unknown column 'gmlevel' in 'field list' at /var/www/AoWoW/includes/allcomments.php line 24
Array
(
    [code] => 1054
    [message] => Unknown column 'gmlevel' in 'field list'
    [query] => SELECT username as user, gmlevel as roles FROM account WHERE id='150' LIMIT 1
    [context] => /var/www/AoWoW/includes/allcomments.php line 24
)

**Comment by ekzobam** [comment]
fixed
