### ISSUE TITLE
sql error when clicking on a gem

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/AoWoW#7]
when you click on a gem you get the follwoing error

SQL Error: Table 'oregon_world.aowow_gemproperties' doesn't exist at /var/www/AoWoW/includes/allitems.php line 309
Array
(
    [code] => 1146
    [message] => Table 'oregon_world.aowow_gemproperties' doesn't exist
    [query] => SELECT aowow_itemenchantmet.text from aowow_itemenchantmet, aowow_gemproperties WHERE (aowow_gemproperties.gempropertiesID=142 and aowow_itemenchantmet.itemenchantmetID=aowow_gemproperties.itemenchantmetID)
    [context] => /var/www/AoWoW/includes/allitems.php line 309
)

**Comment by ekzobam** [comment]
fixed
